### PR TITLE
adding notebooks for result visualization

### PR DESCRIPTION
**Pull request by fengmudong**
Hi @leeping @yudongqiu @j-wags,
I added a directory torsiondrive/torsiondrive/notebooks/ where my visualization notebooks, sample files and configuration file are stored.
Several improvements compared to the original notebook I demoed at the subgroup meeting:
1. support for both 1D and 2D scan.
2. better interactivity - molecular structures are shown by clicking on the scan points on the plot; hover on the plots reads the scan coordinates and energy.
Please review. Thanks.
(my first time doing pull request, might made mistakes, feel free to correct me.)

### CODE REVIEW

**Comment by yudongqiu** [comment]
@fengmudong Thanks a lot for the PR! A few suggestions from my initial reading:

1. The `torsiondrive/torsiondrive` folder is purely for source codes that are going to be packaged and distributed, so I think it's better to move the notebooks folder from `torsiondrive/torsiondrive/notebooks/` to `torsiondrive/notebooks`

2. There are a few example files like `scan.pdb`, `scan.xyz` in the `notebooks/` folder. As you know that we are now trying to put all example in a separate [repository](https://github.com/lpwgroup/torsiondrive_examples) There are already 1-D and 2-D examples with result `scan.xyz` files in there but if you want to include some new examples it might be good to make a PR there.

I will try to go over the codes in the notebooks and let you know if I have further feedbacks.

Thanks!

**Comment by fengmudong** [comment]
@yudongqiu Thanks for the suggestion. With my last commit, 2d example now uses scan.xyz from torsiondrive_examples/range_limited, and notebooks directory is moved according to your suggestions.

**Comment by yudongqiu** [comment]
Hi @fengmudong,

Sorry for the delay on the merging. 

After reading though your scripts carefully, I think the ideas are great and I also learned about using `plotly` and `nglview`.

I found many places in the script that I want to improve, and I think going back and forth with you about each individual change will take a long time, so I proceeded by rewriting the scripts myself. 

Some major improvements include:
- Download `scan.xyz` from the `torsiondrive_examples` repository, so the large data files do not need to be included in the repo.

- Reuse functions in `torsiondrive.tools` to parse the `scan.xyz` file. These functions can support loading "incomplete scans" that may be limited in range or by energy.

- Rewrote the `nglview` viewing functions. Now the structure is loaded once as a trajectory, and clicking the plot will select the corresponding frame in the trajectory. This helps to solve issues with temporary pdb files and performance. Also, it is not required for the user to generate `scan.pdb` any more.

- Improved the `plotly` interactive plot features. For the 1-D plot, selected points will have a larger size and a different color, so the user can always know which point is currently selected.

The new scripts are pushed to a branch, `pr-41`. Please check it out and let me know if they make sense to you. Here are some steps you might need:

1. Create a new conda environment for torsionsdrive dev:
    ```
    conda create -n tddev python pip
    conda activate tddev
    ```

2. Checkout the remote branch, [ref](https://help.github.com/en/articles/syncing-a-fork):
    ```
    cd torsiondrive
    ```

    add remote upstream if you haven't done so before
    ```
    git remote add upstream https://github.com/lpwgroup/torsiondrive.git
    ```

    Checkout the branch
    ```
    git fetch upstream
    git checkout upstream/pr-41
    ```

3. Install current code into dev environment, install required packages:
    ```
    python setup.py install
    conda install -c conda-forge matplotlib plotly nglview ipywidgets
    jupyter-nbextension enable nglview --py --sys-prefix
    ```

4. Try the notebooks
    ```
    cd notebooks/
    jupyter-notebook
    ```

5. If everything looks good, merge this into your master branch so the PR is updated.
    ```
    git checkout master
    git merge upstream/pr-41
    git push origin master
    ```

**Comment by fengmudong** [comment]
Thanks a lot for the improvements made in the code and the very lucid instructions!

I configured and executed the notebooks and they are great overall. A minor representation issue:
Screenshot from 2019-05-09 12-41-22
It seems that the picked conformation is overlayed on the first frame conformation, making the visualization a bit unclear. I think it would be better to either show only the picked conformtion, or to show both structures in a clearer representation (maybe ball stick with different colors).

I updated the PR.

**Comment by yudongqiu** [comment]
@fengmudong Thanks for the quick update! I did not see this issue in my environment. 
I have `nglview 1.2.1` running with `ipywidgets 7.4.2` and `notebook 5.7.8`. And the notebook was opened in Chrome browser on Mac.
Could you please show me the versions of the above packages you have?

**Comment by fengmudong** [comment]
@yudongqiu 
I have the same versions for nglview, ipywidgets, but my notebook version is different.
`jupyter_client            5.2.4                      py_3    conda-forge`
`jupyter_core              4.4.0                      py_0    conda-forge`
I'm using Linux and chrome.
Also I tried `conda install jupyter` which gave me
`jupyter                   1.0.0                      py_2    conda-forge`
`jupyter_client            5.2.4                      py_3    conda-forge`
`jupyter_console           6.0.0                      py_0    conda-forge`
`jupyter_core              4.4.0                      py_0    conda-forge`
But the same problem still happens.

**Comment by yudongqiu** [comment]
Thanks! I will try it on linux and fix the issue in the next update. Merging.

**Comment by yudongqiu** [comment]
@fengmudong I tested it on Linux and it turns out to be a bug in nglview. I have filed a bug report here: 
https://github.com/arose/nglview/issues/799

**Comment by fengmudong** [comment]
@yudongqiu Great, thank you!

**Pull request merged**
